config/routes.rb
Rails.application.routes.draw do
  get '/home', to: 'home#index', as: 'home'
  get '/contatti', to: 'home#contatti', as:'contatti'
  get '/colazione', to: 'home#colazione', as:'colazione'
  get '/pranzo', to: 'home#pranzo', as:'pranzo'
  get '/merenda', to: 'home#merenda', as:'merenda'
  get '/cena', to: 'home#cena', as:'cena'
  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index  
    end
    def contatti
    end
    def colazione
    end
    def pranzo
    end
    def merenda
    end
    def cena
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/colazione.html.erb
<div class='flex-col flex items-center gap-5'>
    <img
        alt="Colazione initial image"
        class="flex relative w-screen h-16:9"
        src="/images/giuseppino.jpg"
    >
        <h1 class="text-7xl text-white absolute drop-shadow-lg">COLAZIONE</h1>
    <img/>
    <p class="text-base">
        Per una colazione equilibrata, scegli alimenti che ti diano energia e sazietà. Opta per una fonte di proteine, come yogurt greco o uova, accompagnata da carboidrati complessi, come pane integrale o fiocchi d’avena. Aggiungi frutta fresca per vitamine e fibre e una manciata di frutta secca o semi per i grassi sani. Evita zuccheri raffinati e prediligi bevande come tè, caffè o latte senza troppi dolcificanti.
    </p>
</div>

app/views/home/contatti.html.erb
<div class="flex-col flex ">
    <p class="text-3xl font-bold">
        Contact Cage
    </p>
    <%= link_to 'Torna alla Home', home_path %>
</div>

app/views/home/index.html.erb
<div class='flex-col flex container items-center'>
    <%= image_tag '/images/giuseppino.jpg', class:"w-100" %>
</div>

app/views/layouts/_footer.html.erb
<div class='flex-row flex items-center justify-center gap-5 mt-5 text-2xl'>
    <%= link_to 'Home', home_path, class: 'text-white bg-black p-3 border-1 border-black rounded-2xl' %>
    <%= link_to 'Contatti', contatti_path, class: 'text-white bg-black p-3 border-1 border-black rounded-2xl' %>
    <%= link_to 'Colazione', colazione_path, class: 'text-white bg-black p-3 border-1 border-black rounded-2xl' %>
    <%= link_to 'Pranzo', pranzo_path, class: 'text-white bg-black p-3 border-1 border-black rounded-2xl' %>
    <%= link_to 'Merda', merenda_path, class: 'text-white bg-black p-3 border-1 border-black rounded-2xl' %>
    <%= link_to 'Cena', cena_path, class: 'text-white bg-black p-3 border-1 border-black rounded-2xl' %>
</div>

app/views/layouts/_navbar.html.erb
<div class='flex-row flex items-center gap-5 mb-5 text-2xl'>
    <%= image_tag '/images/icon.png', class:"w-30" %>
    <%= link_to 'Home', home_path, class: '' %>
    <%= link_to 'Contatti', contatti_path, class: '' %>
    <%= link_to 'Colazione', colazione_path, class: '' %>
    <%= link_to 'Pranzo', pranzo_path, class: '' %>
    <%= link_to 'Merda', merenda_path, class: '' %>
    <%= link_to 'Cena', cena_path, class: '' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Dolci Delizie" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= render partial: 'layouts/navbar' %>
    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="flex-col flex ">
      <%= yield %>
      <%= render partial: 'layouts/footer' %>
    </main>
  </body>
</html>